# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLikedSongs():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_likedSongs(self):
    self.driver.get("https://checkout.stripe.com/c/pay/cs_test_b1Xk4nAHUAbHSdYjm1ZWG3dSuxFsiBELHcClufj0MUpO0GmroI0t2v8T0J#fidkdWxOYHwnPyd1blpxYHZxWjA0VTFrNkhWQTVhUEZDd3dsdU9TRmswPFc0N2hdUE5LdFNETjRsRG9tVlBuZHY2fDR0S1B2a0pBbzJoR1ZSQHcxTEt%2FNz1nTENOSkZQajVPYnRncWZ%2FT0pPNTUzYmlQUzxTSScpJ2hsYXYnP34nYnBsYSc%2FJzc3N2E3NGcyKGc2PTEoMTIyNCg9YGNgKGBjMjBkZmMyM2NhYGY3Yz0yNycpJ2hwbGEnPycwMDJgYT1nMCg1MzA3KDE2MjMoPWc0NyhjNjY8Z2dnZDxgZGE1YWMyN2AnKSd2bGEnPydmMGMzYTw1Nyg9PDxkKDEzN2EoZDZhNShmNmYxYGA2MDY1MzcxNj09ZGYneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8naHBpcWxabHFgaCcpJ3dgY2B3d2B3SndsYmxrJz8nbXFxdT8qKmlqZmRpbWp2cT82NTU1J3gl/")
    self.driver.set_window_size(708, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".py-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-full:nth-child(1) > .text-black > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(5) .object-cover").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-x-4 > .cursor-pointer > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) .object-cover").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-x-4 > .cursor-pointer path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-x-4:nth-child(2) > .cursor-pointer path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > .hover\\3Aopacity-75 path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-2:nth-child(1) > .text-black").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex-col:nth-child(1) > .relative > .object-cover").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-x-4 > .cursor-pointer > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-5").click()
  
