# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStripeGateway():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_stripeGateway(self):
    self.driver.get("https://checkout.stripe.com/c/pay/cs_test_b1Xk4nAHUAbHSdYjm1ZWG3dSuxFsiBELHcClufj0MUpO0GmroI0t2v8T0J#fidkdWxOYHwnPyd1blpxYHZxWjA0VTFrNkhWQTVhUEZDd3dsdU9TRmswPFc0N2hdUE5LdFNETjRsRG9tVlBuZHY2fDR0S1B2a0pBbzJoR1ZSQHcxTEt%2FNz1nTENOSkZQajVPYnRncWZ%2FT0pPNTUzYmlQUzxTSScpJ2hsYXYnP34nYnBsYSc%2FJzc3N2E3NGcyKGc2PTEoMTIyNCg9YGNgKGBjMjBkZmMyM2NhYGY3Yz0yNycpJ2hwbGEnPycwMDJgYT1nMCg1MzA3KDE2MjMoPWc0NyhjNjY8Z2dnZDxgZGE1YWMyN2AnKSd2bGEnPydmMGMzYTw1Nyg9PDxkKDEzN2EoZDZhNShmNmYxYGA2MDY1MzcxNj09ZGYneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8naHBpcWxabHFgaCcpJ3dgY2B3d2B3SndsYmxrJz8nbXFxdT8qKmlqZmRpbWp2cT82NTU1J3gl")
    self.driver.set_window_size(708, 816)
    self.driver.find_element(By.ID, "cardNumber").click()
    self.driver.find_element(By.ID, "cardNumber").send_keys("4000 3750 3680 1650")
    self.driver.find_element(By.ID, "cardExpiry").click()
    self.driver.find_element(By.ID, "cardExpiry").send_keys("12 / 29")
    self.driver.find_element(By.ID, "cardCvc").click()
    self.driver.find_element(By.ID, "cardCvc").send_keys("758")
    self.driver.find_element(By.ID, "billingName").click()
    self.driver.find_element(By.ID, "billingName").send_keys("dia Palathingal")
    self.driver.find_element(By.ID, "billingCountry").click()
    self.driver.find_element(By.ID, "billingAddressLine1").click()
    self.driver.find_element(By.ID, "billingAddressLine1").send_keys("Varangal")
  
